name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build project
      uses: threeal/cmake-action@2.1.0
      with:
        build-dir: output
        cxx-compiler: clang++
